#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey -v

alias vim="nvim"
alias xc="xclip -selection c"

# cargo configuration
export PATH="$HOME/.cargo/bin:$PATH"

# OPAM configuration
. /home/lasagnaphil/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# npm configuration
export PATH=~/.npm-global/bin:$PATH

# zsh
export SHELL=/bin/zsh

# xdg-open
alias open=xdg-open

# run ocaml with prettier error messages
ocamlp() {
    ocaml $1 2>&1 | berror
}

# autoloads
autoload -Uz zmv
autoload -Uz zcp

# marp
alias marp=~/Programs/marp/Marp

# env for identifying if this computer is Arch Linux
export ARCHLINUX=1

# nvm settings
export NVM_DIR="$HOME/.nvm"
export NVM_SOURCE="/usr/share/nvm"
[ -s "$NVM_SOURCE/nvm.sh" ] && . "$NVM_SOURCE/nvm.sh"
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# default terminal
export TERMINAL=termite

# RVM settings
eval "$(rbenv init -)"

[ -s ~/.luaver/luaver ] && . ~/.luaver/luaver

# shortcuts related to awesomewm
function xephyr() { Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome }

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval $(thefuck --alias)
